ci: upgrade Rust in CI contract building test
This PR upgrade Rust to 1.57.0 in some part of CI.
When CI uses rust 1.51,
error: linking with `cc` failed: exit code: 1
is caused in mac OS v12.