feat: add interface validation method for dynamic link functions (#245)
* feat: add get_wasmer_module to backend api

* feat: add validate interface to api

* feat: make dynamic_link macro which adds validate interface automatically

* feat: update dynamic caller contract to use interface detection and
update contracts depending cosmwasm

* doc: add some comments

* ci: upgrade Rust in CI contract building test

This PR upgrade Rust to 1.57.0 in some part of CI.
When CI uses rust 1.51,
error: linking with `cc` failed: exit code: 1
is caused in mac OS v12.

* fix: modify a error message